### ISSUE TITLE
set up CI to render package website

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/casteval#1]
tried this quickly with `usethis::use_github_action("pkgdown")`, workflow failed when trying to install dependencies. our `pkgdown` site should deploy using the package dependencies from DESCRIPTION, if all is set up correctly, so something is probably wonky there, probably because we also use `renv` to manage the project dependencies, so we've probably been able to get away with this locally. 

`usethis::use_github_action("pkgdown")` sets up a workflow that doesn't use `renv` and instead installs dependencies with

```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
```

([source](https://github.com/r-lib/actions/tree/v2-branch/examples#build-pkgdown-site))

i tried adding `- uses: r-lib/actions/setup-renv@v2` before this step to get the `renv` environment to restore in case that helped---it didn't. i also tried replacing the `setup-r-dependencies` action with `setup-renv@v2`, also didn't work. boo!
